install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe'
  - rustup-init.exe -y --default-host x86_64-pc-windows-gnu --default-toolchain stable
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

build_script:
  - cargo build --verbose
  - cargo build --verbose --no-default-features

test_script:
  - cargo test --verbose
  - cargo test --verbose --no-default-features
