[package]

name = "prettytable-rs"
version = "0.6.6"
description = "A library for printing pretty formatted tables in terminal"
homepage = "https://github.com/phsym/prettytable-rs"
repository = "https://github.com/phsym/prettytable-rs"
documentation = "http://phsym.github.io/prettytable-rs"
readme = "README.md"
authors = [ "Pierre-Henri Symoneaux" ]
keywords = ["tab", "table", "format", "pretty", "print"]
categories = ["command-line-interface"]
license = "BSD-3-Clause"

[features]
default = ["win_crlf", "csv"]
win_crlf = []

[[bin]]
name = "main"

[lib]
name = "prettytable"

[dependencies]
unicode-width = "^0.1"
term = "^0.4"
lazy_static = "^0.2"
atty = "^0.2"
encode_unicode = "^0.3"
csv = { version = "^0.15", optional = true }
