[package]

name = "prettytable-rs"
version = "0.5.0"
description = "A library for printing pretty formatted tables in terminal"
homepage = "https://github.com/phsym/prettytable-rs"
repository = "https://github.com/phsym/prettytable-rs"
documentation = "http://phsym.github.io/prettytable-rs"
readme = "README.md"
authors = [ "Pierre-Henri Symoneaux" ]
keywords = ["tab", "table", "format", "pretty", "aligned", "terminal", "print"]
license = "BSD-3-Clause"

[[bin]]

name = "main"

[lib]
name = "prettytable"

[dependencies]
unicode-width = "*"
term = "*"
