[package]

name = "prettytable-rs"
version = "0.1.0"
description = "A small rust library that print aligned and formatted tables"
repository = "https://github.com/phsym/tabprint"
readme = "README.md"
authors = [ "Pierre-Henri Symoneaux" ]
keywords = ["tab", "table", "format", "pretty", "aligned"]
license = "BSD-3-Clause"

[[bin]]

name = "main"

[lib]
name = "prettytable"